# The nutrition value this food provides.
nutrition: 14
# The saturation this food provides.
saturation: 21.0
# Whether the food can always be eaten, or only when hungry.
can_always_eat: false
# The time it takes for the food to be consumed, in ticks.
consume_time: 40
# The item stack that remains after the food is consumed.
remains: "minecraft:bowl"
# A list of effects to apply to the player when this food is consumed.
possible_effects: []