# The nutrition value this food provides.
nutrition: 7
# The saturation this food provides.
saturation: 8.4
# Whether the food can always be eaten, or only when hungry.
can_always_eat: true
# The time it takes for the food to be consumed, in ticks.
consume_time: 40
# The item stack that remains after the food is consumed.
remains: "minecraft:glass_bottle"
# A list of effects to apply to the player when this food is consumed.
possible_effects:
  - type: glowing
    duration: 100
    amplifier: 0
    ambient: true
    particles: true
    icon: true
    probability: 0.3